#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "===\n>> Pre-push Hook: Checking branch name"

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|develop|staging)"

echo -e "\n $BRANCH $PROTECTED_BRANCHES" && exit 1
if [[ $1 != *"$BRANCH"* ]]
then
  echo -e "\n🚫 You must use (git push origin $BRANCH).\n" && exit 1
fi

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and initiate a Merge Request.\n" && exit 1
fi

echo -e ">> Finished checking branch name.\n==="

exit 0